trigger:
  branches:
    include:
      - master
      - rel/*
  paths:
    include:
      - src/SignClient/*
      - .editorconfig
      - .vsts.client.ci.yml
      - version.json
      - scripts/*

queue: Hosted VS2017
variables: 
  BuildConfiguration: Release

steps:
- task: DotNetCoreInstaller@0
  inputs:
    version: '2.1.300'

- task: DotNetCoreCLI@2
  inputs:
    command: pack
    packagesToPack: src/SignClient/SignClient.csproj
    packDirectory: $(Build.ArtifactStagingDirectory)\Client
    configuration: $(BuildConfiguration)
  displayName: Build Client

- task: PowerShell@2
  displayName: Authenticode Sign Client artifacts
  inputs:
    filePath: scripts/Sign-Package.ps1
  env:
    SignClientUser: $(SignClientUser)
    SignClientSecret: $(SignClientSecret)
    ArtifactDirectory: $(Build.ArtifactStagingDirectory)\Client
  condition: eq(variables['system.pullrequest.isfork'], false)

- task: PublishBuildArtifacts@1
  displayName: Publish SignClient Artifact
  inputs:
    pathToPublish: $(Build.ArtifactStagingDirectory)\Client
    artifactType: container
    artifactName: SignClient
  condition: eq(variables['system.pullrequest.isfork'], false)